C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapRInvNorm (RInvNormf2pywrap, P)
      external RInvNorm
      real P
      real RInvNormf2pywrap, RInvNorm
      RInvNormf2pywrap = RInvNorm(P)
      end


      subroutine f2pyinitdist(setupfunc)
      external setupfunc
      real alphar
      real betar
      real cnfint
      real rmin
      real rmax
      real sdnrm
      common /dist/ alphar,betar,cnfint,rmin,rmax,sdnrm
      call setupfunc(alphar,betar,cnfint,rmin,rmax,sdnrm)
      end

      subroutine f2pyinitparam(setupfunc)
      external setupfunc
      real bound
      real cmptln
      real dtheta
      real eps
      real height
      integer nc
      integer n               npart_kz
      real pi
      real porosity
      real rlmt
      integer nrndsd
      real size_bn
      real theta
      real tolrnce
      integer ncz
      common /param/ bound,cmptln,dtheta,eps,height,nc,n          
     &     npart_kz,pi,porosity,rlmt,nrndsd,size_bn,theta,tolrnce,ncz
      call setupfunc(bound,cmptln,dtheta,eps,height,nc,n          
     &     npart_kz,pi,porosity,rlmt,nrndsd,size_bn,theta,tolrnce,ncz)
      end

      subroutine f2pyinitlocal(setupfunc)
      external setupfunc
      integer intensity
      integer lshift
      integer move
      common /local/ intensity,lshift,move
      call setupfunc(intensity,lshift,move)
      end

      subroutine f2pyinitcorr(setupfunc)
      external setupfunc
      integer ncor
      real gridln
      integer Ngrid
      integer Nzgrid
      integer mr
      common /corr/ ncor,gridln,Ngrid,Nzgrid,mr
      call setupfunc(ncor,gridln,Ngrid,Nzgrid,mr)
      end

      subroutine f2pyinitindex(setupfunc)
      external setupfunc
      integer mcount
      integer movlpcond
      integer mpBC
      integer mroll
      integer nrec
      integer ntshift
      integer niterate
      common /index/ mcount,movlpcond,mpBC,mroll,nrec,ntshift,nite
     &rate
      call setupfunc(mcount,movlpcond,mpBC,mroll,nrec,ntshift,nite
     &rate)
      end

      subroutine f2pyinitorigdim(setupfunc)
      external setupfunc
      real r(100000)
      real rc(200,200,200)
      real x(100000)
      real xc(200,200,200)
      real y(100000)
      real yc(200,200,200)
      real z(100000)
      real zc(200,200,200)
      integer icnt(200,200)
      common /origdim/ r,rc,x,xc,y,yc,z,zc,icnt
      call setupfunc(r,rc,x,xc,y,yc,z,zc,icnt)
      end

      subroutine f2pyinitMCHCOM(setupfunc)
      external setupfunc
      real BASE
      real DNOT(3)
      real FINITY
      common /MCHCOM/ BASE,DNOT,FINITY
      call setupfunc(BASE,DNOT,FINITY)
      end

      subroutine f2pyinitdata(setupfunc)
      external setupfunc
      integer icst2
      integer icst3
      integer icst4
      integer i1x
      integer i1x1
      integer i1x2
      integer i1x3              jy
      integer jy1
      integer jy2
      integer jy3
      integer jy4
      integer kz
      integer kz1
      integer kz2
      integer kz3
      integer kz4
      real r1
      real r2
      real r3
      real r4
      real x1
      real x2
      real x3
      real x4
      real y1
      real y2
      real y3
      real y4
      real z1
      real z2
      real z3
      real z4
      common /data/ icst2,icst3,icst4,i1x,i1x1,i1x2,i1x3          
     &    jy,jy1,jy2,jy3,jy4,kz,kz1,kz2,kz3,kz4,r1,r2,r3,r4,x1,x2,x3,x4,
     &y1,y2,y3,y4,z1,z2,z3,z4
      call setupfunc(icst2,icst3,icst4,i1x,i1x1,i1x2,i1x3         
     &     jy,jy1,jy2,jy3,jy4,kz,kz1,kz2,kz3,kz4,r1,r2,r3,r4,x1,x2,x3,x4
     &,y1,y2,y3,y4,z1,z2,z3,z4)
      end

      subroutine f2pyinitsortdim(setupfunc)
      external setupfunc
      real rcst(200,200,200,200)
      real xcst(200,200,200,200)
      real ycst(200,200,200,200)
      real zcst(200,200,200,200)
      integer icntst(200,200,200)
      common /sortdim/ rcst,xcst,ycst,zcst,icntst
      call setupfunc(rcst,xcst,ycst,zcst,icntst)
      end

      subroutine f2pyinittmp(setupfunc)
      external setupfunc
      integer mrolltmp
      common /tmp/ mrolltmp
      call setupfunc(mrolltmp)
      end

      subroutine f2pyinitflag(setupfunc)
      external setupfunc
      integer mark
      common /flag/ mark
      call setupfunc(mark)
      end

      subroutine f2pyinitsign(setupfunc)
      external setupfunc
      integer lsign
      common /sign/ lsign
      call setupfunc(lsign)
      end

      subroutine f2pyinitdata1(setupfunc)
      external setupfunc
      real x11
      real x12
      real x13
      real x11max
      real y11
      real y12
      real y13
      real y11               z11
      real z12
      real z11max
      real rxy
      real sineA
      real cosineA
      real sineB
      real cosineB
      common /data1/ x11,x12,x13,x11max,y11,y12,y13,y11           
     &    z11,z12,z11max,rxy,sineA,cosineA,sineB,cosineB
      call setupfunc(x11,x12,x13,x11max,y11,y12,y13,y11           
     &    z11,z12,z11max,rxy,sineA,cosineA,sineB,cosineB)
      end

      subroutine f2pyinitshift(setupfunc)
      external setupfunc
      real xshift(30)
      real yshift(30)
      real zshift(30)
      integer i1xshift(30)
      integer jyshift(30)
      integer kzshift(30)
      integer indx(30)
      common /shift/ xshift,yshift,zshift,i1xshift,jyshift,kzshift
     &,indx
      call setupfunc(xshift,yshift,zshift,i1xshift,jyshift,kzshift
     &,indx)
      end


